version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - php -m
      - php -r "print_r(get_loaded_extensions());"
#  post_build:
#    commands:
#      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
#cache:
#  paths:
#    - '/root/.m2/'
